name: Frontend CI

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'

jobs:
  ci:
    uses: banua-coder/banua-coder-workflow/.github/workflows/ci-node.yml@main
    with:
      node-version: '20'
      package-manager: npm
      working-directory: frontend
      run-lint: true
      run-typecheck: true
      run-tests: false
      run-build: true
      run-coverage: false
      post-coverage-comment: true
